### ISSUE TITLE
Problem with install

### ISSUE THREAD

**Issue by sunftec** [jafaripur/admap#1]
hi. tank you for this big help with this project.
i can't install .
when <code>php composer.phar global require "fxp/composer-asset-plugin:*"</code>
get this error
![aaa](https://cloud.githubusercontent.com/assets/10174535/9390403/b00bdf84-4725-11e5-9d07-5b44a57e054f.png)

when update i get this error
![untitled](https://cloud.githubusercontent.com/assets/10174535/9390178/59a05914-4724-11e5-9472-f8a81783ba63.png)

please help .tnk you ...

**Comment by jafaripur** [comment]
Maybe bower module for composer is not installed. use this command to install bower module:

```
php composer.phar global require "fxp/composer-asset-plugin:*"
```

**Comment by sunftec** [comment]
I use this command but I get above error picture
در تاریخ 20 اوت 2015 22:51، "Jafaripur" notifications@github.com نوشت:

**Comment by jafaripur** [comment]
Use github oAuth Token config in composer config section on this:

```
"config": {
        "github-oauth":{
            "github.com":"YOUR_TOKEN"
        },
        "process-timeout": 1800
    }
```

For more information you can google it.
